spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/login
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: 1234567890123456789012345678901234567890
  access-token:
    expiration: 600000    # 10m
  refresh-token:
    expiration: 86400000 # 24h

server:
  port: 8080
